name: Automerge
on:[pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const checkSuite = await github.checks.listSuitesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.data.head.sha
            });
            const allChecksPassed = checkSuite.data.check_suites.every(suite => {
              return suite.app.name == 'review' || suite.conclusion == 'success';
            });
            if (allChecksPassed) {
              if (pr.data.user.login == context.repo.owner) {
                github.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  event: 'APPROVE'
                })
                github.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number
                })
              }
            }
