name: Automerge
on:
  pull_request:
    types: [labeled]
  check_suite:
    types: [completed]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        if: github.event.label.name == 'npm' && github.event.check_suite.conclusion == 'success'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            if (pr.data.user.login == context.repo.owner) {
              github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: 'APPROVE'
              })
              github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              })
            }
