name: Automerge
on:
  check_suite:
    types: [completed]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const checkSuite = await github.checks.getSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_suite_id: context.payload.check_suite.id
            });
            const allChecksPassed = checkSuite.data.check_runs.every(check => {
              return check.name == 'review' || check.conclusion == 'success';
            });
            if (allChecksPassed) {
              const pr = await github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              });
              if (pr.data.user.login == context.repo.owner) {
                github.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  event: 'APPROVE'
                })
                github.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number
                })
              }
            }
